name: Node Docker Image Scan

on:
  push:
    branches: [ main ]

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo-node:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: demo-node:latest
          format: table
          output: trivy-report.txt
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Upload scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scan-report
          path: trivy-report.txt
